import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

// Legacy starter table is retained for safe, append-only production migrations.
export const items=sqliteTable("items",{id:integer("id").primaryKey({autoIncrement:true}),title:text("title").notNull(),createdAt:text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`)});

const timestamps={createdAt:text("created_at").notNull().default("CURRENT_TIMESTAMP"),updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP")};
export const users=sqliteTable("users",{id:text("id").primaryKey(),name:text("name").notNull(),email:text("email").unique(),phone:text("phone").unique(),role:text("role").notNull(),passwordHash:text("password_hash").notNull(),active:integer("active",{mode:"boolean"}).notNull().default(true),...timestamps});
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>users.id),token:text("token").notNull().unique(),expiresAt:text("expires_at").notNull(),createdAt:text("created_at").notNull().default("CURRENT_TIMESTAMP")});
export const packages=sqliteTable("packages",{id:text("id").primaryKey(),code:text("code").notNull().unique(),name:text("name").notNull(),speedMbps:integer("speed_mbps").notNull(),price:integer("price").notNull(),description:text("description"),active:integer("active",{mode:"boolean"}).notNull().default(true),...timestamps});
export const customers=sqliteTable("customers",{id:text("id").primaryKey(),customerCode:text("customer_code").notNull(),userId:text("user_id").references(()=>users.id),name:text("name").notNull(),phone:text("phone").notNull(),address:text("address").notNull(),latitude:real("latitude"),longitude:real("longitude"),packageId:text("package_id").notNull().references(()=>packages.id),priceSnapshot:integer("price_snapshot").notNull(),installedAt:text("installed_at").notNull(),dueDay:integer("due_day").notNull(),status:text("status").notNull(),notes:text("notes"),deviceInfo:text("device_info"),...timestamps},t=>[uniqueIndex("customers_code_uidx").on(t.customerCode),uniqueIndex("customers_phone_uidx").on(t.phone),index("customers_status_idx").on(t.status)]);
export const invoices=sqliteTable("invoices",{id:text("id").primaryKey(),invoiceNumber:text("invoice_number").notNull().unique(),customerId:text("customer_id").notNull().references(()=>customers.id),packageName:text("package_name").notNull(),period:text("period").notNull(),issuedAt:text("issued_at").notNull(),dueDate:text("due_date").notNull(),amount:integer("amount").notNull(),status:text("status").notNull(),paymentLink:text("payment_link"),...timestamps},t=>[uniqueIndex("invoice_customer_period_uidx").on(t.customerId,t.period),index("invoice_status_due_idx").on(t.status,t.dueDate)]);
export const payments=sqliteTable("payments",{id:text("id").primaryKey(),paymentNumber:text("payment_number").notNull().unique(),invoiceId:text("invoice_id").notNull().references(()=>invoices.id),customerId:text("customer_id").notNull().references(()=>customers.id),amount:integer("amount").notNull(),channel:text("channel").notNull(),method:text("method").notNull(),externalId:text("external_id").unique(),paidAt:text("paid_at").notNull(),staffId:text("staff_id").references(()=>users.id),notes:text("notes"),proofData:text("proof_data"),status:text("status").notNull(),createdAt:text("created_at").notNull().default("CURRENT_TIMESTAMP")},t=>[index("payments_paid_idx").on(t.paidAt)]);
export const settings=sqliteTable("settings",{key:text("key").primaryKey(),value:text("value").notNull(),updatedAt:text("updated_at").notNull().default("CURRENT_TIMESTAMP")});
export const whatsappTemplates=sqliteTable("whatsapp_templates",{id:text("id").primaryKey(),event:text("event").notNull().unique(),name:text("name").notNull(),content:text("content").notNull(),active:integer("active",{mode:"boolean"}).notNull().default(true)});
export const whatsappNotifications=sqliteTable("whatsapp_notifications",{id:text("id").primaryKey(),customerId:text("customer_id").notNull().references(()=>customers.id),invoiceId:text("invoice_id").references(()=>invoices.id),destination:text("destination").notNull(),content:text("content").notNull(),status:text("status").notNull(),sentAt:text("sent_at"),error:text("error")});
export const paymentWebhooks=sqliteTable("payment_webhooks",{eventId:text("event_id").primaryKey(),externalId:text("external_id"),signatureValid:integer("signature_valid",{mode:"boolean"}).notNull(),status:text("status").notNull(),sanitizedPayload:text("sanitized_payload"),createdAt:text("created_at").notNull().default("CURRENT_TIMESTAMP")});
export const auditLogs=sqliteTable("audit_logs",{id:text("id").primaryKey(),actorId:text("actor_id").references(()=>users.id),action:text("action").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id"),summary:text("summary").notNull(),ip:text("ip"),userAgent:text("user_agent"),createdAt:text("created_at").notNull().default("CURRENT_TIMESTAMP")},t=>[index("audit_created_idx").on(t.createdAt)]);
